name: bosque_flutter
description: "Bosque"
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.0
  dio: ^5.8.0+1
  dropdown_search: ^6.0.2
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  pluto_grid: ^8.0.0
  printing: ^5.14.2
  responsive_framework: ^1.5.1
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_native_splash: ^2.4.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/logo.png"
  android_12:
    image: "assets/icon/logo.png"
    color: "#ffffff"
    icon_background_color: "#ffffff"
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf