name: bosque_flutter
description: "Bosque"
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.0
  dio: ^5.8.0+1
  dropdown_search: ^6.0.2
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  pluto_grid: ^8.0.0
  printing: ^5.14.2
  responsive_framework: ^1.5.1
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

# Configuración de iconos para todas las plataformas
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21 # Android 5.0
  
  # Configuración específica para Android
  android_12:
    image_path: "assets/icon/logo.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/icon/logo.png"
  
  # Configuración para diferentes tamaños de Android
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/logo.png"
  
  # Configuración para web
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  
  # Configuración para Windows
  windows:
    generate: true
    image_path: "assets/icon/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  
  # Configuración para macOS
  macos:
    generate: true
    image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf