name: bosque_flutter
description: "Bosque"
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: ^3.7.2

dependencies:
  awesome_snackbar_content: ^0.1.1
  dio: ^5.8.0+1
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_map: ^8.1.1
  flutter_map_cancellable_tile_provider: ^3.1.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_speed_dial: ^7.0.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  graphview: ^1.5.0
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  latlong2: ^0.9.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  phone_numbers_parser: ^8.0.0
  pluto_grid: ^8.0.0
  printing: ^5.14.2
  responsive_framework: ^1.5.1
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/
    - assets/icon/whatsapp.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
