class LoteProduccionEntity {
  int idMa;
  int idLp;
  int numLote;
  int anio;
  DateTime fecha;
  String hraInicioCorte;
  String hraInicio;
  String hraFin;
  int cantBobinasIngresoTotal;
  double pesoKilosTotalIngreso;
  double pesoTotalSalida;
  double pesoPaletaSalida;
  double pesoMaterialSalida;
  int cantResmaSalida;
  double cantHojasSalida;
  double mermaTotal;
  double diferenciaProduccion;
  double diferenciaProdResma;
  double cantEstimadaResma;
  double pesoBalanzaTotal;
  int estado;
  String obs;
  int numCorte;
  int anioCorte;
  int docNumOrdFab;
  int codEmpresa;
  int audUsuario;
  String codArticulo;
  String datoArt;
  String articulo;
  double utm;
  String codArtEntrada;
  String codArtSalida;
  String db;

  LoteProduccionEntity({
    required this.idMa,
    required this.idLp,
    required this.numLote,
    required this.anio,
    required this.fecha,
    required this.hraInicioCorte,
    required this.hraInicio,
    required this.hraFin,
    required this.cantBobinasIngresoTotal,
    required this.pesoKilosTotalIngreso,
    required this.pesoTotalSalida,
    required this.pesoPaletaSalida,
    required this.pesoMaterialSalida,
    required this.cantResmaSalida,
    required this.cantHojasSalida,
    required this.mermaTotal,
    required this.diferenciaProduccion,
    required this.diferenciaProdResma,
    required this.cantEstimadaResma,
    required this.pesoBalanzaTotal,
    required this.estado,
    required this.obs,
    required this.numCorte,
    required this.anioCorte,
    required this.docNumOrdFab,
    required this.codEmpresa,
    required this.audUsuario,
    required this.codArticulo,
    required this.datoArt,
    required this.articulo,
    required this.utm,
    required this.codArtEntrada,
    required this.codArtSalida,
    required this.db,
  });
}
